var Frases = new Array()
/*P1 T1-T11*/
Frases[0] = ["Un senyal és una magnitud o paràmetre variable que conté informació, la qual existeix gràcies, precisament, a l'esmentada variabilitat.",1];
Frases[1] = ["La capacitat d'una bateria resulta de dividir l'energia emmagatzemada en ella per la seva tensió nominal i permet determinar el temps que la bateria pot estar subministrant un corrent donat.",1];
Frases[2] = ["S'anomenen sensors als actuadors caracteritzats per convertir senyals no elèctrics en senyals elèctrics. ",0];
Frases[3] = ["Els sistemes digitals són, en la seva immensa majoria, sistemes binaris, és a dir, sistemes que treballen amb senyals que només poden presentar dos valors, que corresponen a dos intervals de tensió o de corrent clarament diferenciats.",1];
Frases[4] = ["Un senyal digital és una magnitud elèctrica variable en el temps que conté informació que pot presentar infinits valors diferents quan la informació es troba en el valor instantani de dita magnitud.",0];
Frases[5] = ["Un sistema electrònic és un cas especial de sistema elèctric integrat per components estàtics, dels quals algun permet controlar el flux d'electrons, i que té com a únic objectiu processar la informació present en els seus senyals elèctrics d'entrada.",0];
Frases[6] = ["Un senyal es qualifica d'analògic quan la informació que conté pot presentar infinits valors diferents.",1];
Frases[7] = ["Es té una bateria de 3 V i una capacitat de 10 Ah amb la que s'alimenta un sistema electrònic que consumeix 250 mW. L'autonomia d'aquest sistema és de 5 dies.",1];
Frases[8] = ["Els sistemes d'instrumentació electrònica acostumen a ser sistemes electrònics de senyal de tipus mixt analògic/digital que estan combinats amb sensors, actuadors i sistemes electrònics de potència.",1];
Frases[9] = ["Un sistema pot ser qualificat de sistema electrònic si els senyals que tracta són senyals electrònics.",0];
Frases[10] = ["Si una font d'alimentació contínua de 12 V alimenta una càrrega resistiva de 1 Ω durant deu minuts, l'energia consumida és de 24 W·hora",1];
Frases[11] = ["És possible emmagatzemar els senyals analògics directament en forma de tensions o corrents variables de forma contínua en el temps.",0];
Frases[12] = ["En cas de processament complex, el processament analògic presenta dificultat de realització i cost elevat d'implementació.",1];
Frases[13] = ["El consum d'un sistema electrònic ve donat pels corrents subministrats per les fonts de tensió contínua que l'alimenten.",1];
Frases[14] = ["La informació present en els senyals d'un sistema electrònic de senyal és digital quan només pot presentar un nombre finit de valors, representables amb un número finit de dígits.",1];
Frases[15] = ["S'anomenen sistemes analògics a aquells sistemes electrònics de senyal caracteritzats perquè la informació present en tots els senyals del sistema (entrades, sortides i senyals intermedis) és analògica.",1];
Frases[16] = ["Un actuador és un transductor que converteix senyals no elèctrics en senyals elèctrics.",0];
Frases[17] = ["Una electrovàlvula pot formar part d'un sistema d'instrumentació electrònica, però no d'un sistema electrònic.",1];
Frases[18] = ["El processament analògic subministra una resposta contínua en magnitud i en el temps",1];
Frases[19] = ["El processament analògic té una baixa precisió degut a l'existència de soroll.",1];
Frases[20] = ["El processament digital permet fer processaments molt complexos a cost molt baix.",1];
Frases[21] = ["És usual convertir informació analògica a digital a fi de processar-la digitalment.",1];
Frases[22] = ["Amb un sistema electrònic, més els actuadors apropiats, és possible processar les informacions presents en senyals no elèctrics propis d'altres sistemes.",0];
Frases[23] = ["Un sistema d'instrumentació electrònica acostuma a incloure un sistema electrònic de senyal de tipus mixt analògic/digital.",1];
Frases[24] = ["Un sistema d'instrumentació electrònica inclou sensors i/o actuadors. ",1];
Frases[25] = ["Si un sistema d'instrumentació electrònica inclou sensors, aquests transformen una magnitud no elèctrica en un senyal elèctric.",1];
Frases[26] = ["Si un sistema d'instrumentació electrònica inclou actuadors, aquests transformen un senyal elèctric en una magnitud no elèctrica.",1];
Frases[27] = ["Els sistemes d'instrumentació electrònica mai inclouen sistemes electrònics de potència.",0];
Frases[28] = ["Un transductor és un dispositiu que converteix un senyal d'un cert tipus físic en un altre senyal d'un tipus físic diferent.",1];
Frases[29] = ["Alguns sistemes d'instrumentació electrònica capten informació del món real, processen aquesta informació electrònicament i subministren els resultats d'aquest processament.",1];
Frases[30] = ["En un sistema electrònic ha d'haver, si més no, un component estàtic que permeti controlar el flux d'electrons.",1];
Frases[31] = ["L'objectiu dels sistemes electrònics és processar la informació o el flux d’energia associats als seus senyals elèctrics.",1];
Frases[32] = ["La capacitat d'una bateria es mesura en Ah i s'obté dividint l'energia que es pot emmagatzemar en ella per la seva tensió nominal.",1];
Frases[33] = ["Un senyal és una magnitud variable que conté informació.",1];
Frases[34] = ["Els sistemes electrònics necessiten d'una font d'energia elèctrica per poder funcionar.",1];
Frases[35] = ["Per alimentar sistemes electrònics autònoms, solen emprar-se bateries recarregables o d'un sol ús.",1];
Frases[36] = ["Una font d'alimentació és un sistema electrònic de potència que converteix l'energia elèctrica d'una font primària en energia elèctrica associada a una tensió contínua.",1];
Frases[37] = ["El consum d'un sistema electrònic ve donat pels corrents subministrats per les fonts de tensió contínua que l'alimenten.",1];
Frases[38] = ["S'anomena capacitat d'una bateria al màxim corrent que pot subministrar.",0];
Frases[39] = ["En alguns casos, el senyal modulat s'obté multiplicant el senyal modulador pel senyal portador.",1];
Frases[40] = ["Un senyal modulat rectangular, és a dir, un senyal amb les característiques pròpies d'un senyal digital binari, pot incloure informació analògica discreta en el temps.",1];
Frases[41] = ["Un senyal modulat rectangular, és a dir, un senyal amb les característiques pròpies d'un senyal digital binari, pot incloure informació analògica contínua en el temps.",0];
Frases[42] = ["En els sistemes que transporten informació a distància sense diferir-la en el temps, el senyal que transporta la informació s'anomena senyal modulat.",1];
Frases[43] = ["En els sistemes que transporten informació a distància sense diferir-la en el temps, el senyal que conté inicialment la informació, s'anomena senyal modulador.",1];
Frases[44] = ["En els sistemes que transporten informació a distància sense diferir-la en el temps, per obtenir el senyal modulat a partir del senyal modulador, s'opera el senyal modulador amb un altre senyal, anomenat senyal portador.",1];
Frases[45] = ["Per transmetre informació, tant analògica com digital, a distància es poden emprar les ones de radiofreqüència (300 Hz a 300 GHz, si s'inclouen les microones).",1];
Frases[46] = ["Per transmetre informació, tant analògica com digital, a distància es poden emprar els infrarojos (300 GHz a 450 THz) i la llum visible (450 THz a 750 THz).",1];
Frases[47] = ["Per transmetre informació, tant analògica com digital, a distància es poden emprar els senyals elèctrics.",1];
Frases[48] = ["En relació als senyals modulat, modulador i portador, la informació que conté el senyal modulat pot ser diferent de la que conté el senyal modulador.",0];
Frases[49] = ["En relació als senyals modulat, modulador i portador, el senyal modulador és el senyal que conté inicialment la informació.",1];
Frases[50] = ["En relació als senyals modulat, modulador i portador, el senyal modulat és el senyal que es transmet.",1];
Frases[51] = ["En relació als senyals modulat, modulador i portador, en el senyal modulat la informació pot estar continguda en varis paràmetres, com l'amplitud i la fase.",1];
Frases[52] = ["Es pot incloure informació digital discreta en el temps en un senyal portador sinusoïdal.",1];
Frases[53] = ["Es pot incloure informació analògica contínua en el temps en un senyal portador sinusoïdal.",1];
Frases[54] = ["La modulació en l'amplada del pols (PWM) permet ubicar informació discreta en amplitud i contínua en el temps sobre un senyal rectangular.",0];
Frases[55] = ["És possible ubicar informació en tres paràmetres diferents d'un senyal sinusoïdal: en l'amplitud A, en la freqüència f i en la fase φ.",1];
Frases[56] = ["La representació gràfica de la conversió analògica-digital és un conjunt finit de punts.",0];
Frases[57] = ["Els sistemes electrònics de senyal es caracteritzen, tots ells, per processar la informació discreta present en els seus senyals d'entrada.",0];
Frases[58] = ["Els transductors són actuadors que converteixen senyals elèctrics en senyals no elèctrics.",0];
Frases[59] = ["Un senyal binari és un senyal digital que conté una informació discreta que només pot prendre dos valors.",1];
Frases[60] = ["Dues bateries d'idèntica capacitat emmagatzemen la mateixa energia elèctrica.",0];
Frases[61] = ["Un sistema electrònic s'alimenta amb una font de contínua de 5 V. El seu consum es pot indicar tant en mA com en mW.",1];
Frases[62] = ["Un senyal analògic és discret en el temps quan la informació que conté, usualment en el seu valor instantani, pot variar en qualsevol instant de temps.",0];
Frases[63] = ["Un sistema digital té per objectiu principal el processament d'informació per mitjans electrònics.",1];
Frases[64] = ["Un sistema analògic té per objectiu principal el processament d'informació per mitjans electrònics.",1];
Frases[65] = ["Un sistema electrònic de potència té per objectiu principal el processament d'informació per mitjans electrònics.",0];
Frases[66] = ["Un sistema electrònic de senyal té per objectiu principal el processament d'informació per mitjans electrònics.",1];
Frases[67] = ["El disseny de sistemes electrònics es pot considerar des de tres punts de vista o dominis: el domini del comportament, el domini estructural i el domini físic.",1];
Frases[68] = ["Tots els connectors negatius de les fonts de tensió emprades al laboratori estan connectats entre si i també ho estan als connectors de terra i al xassís de l'instrument.",0];
Frases[69] = ["Es pot considerar el disseny de sistemes electrònics des de tres punts de vista o dominis: modelat, simulació i implementació.",0];
Frases[70] = ["En la síntesi d'un sistema electrònic es passa del domini del comportament al domini físic a través del domini estructural.",1];
Frases[71] = ["S'anomena circuit integrat a un circuit electrònic implementat sobre un únic cristall de material metàl·lic, el qual s'empaqueta adientment emprant encapsulats estandarditzats que disposen de terminals per a les entrades, sortides i alimentacions del circuit.",0];
Frases[72] = ["Els editors d'esquemàtics elaboren l'estructura del disseny interconnectant una sèrie de símbols gràfics que representen blocs funcionals, que acostumen a disposar d'una sèrie de paràmetres.",1];
Frases[73] = ["Un multímetre és un aparell que subministra tensions elèctriques poc energètiques i variables en el temps, habitualment de tipus sinusoïdal, rectangular i triangular.",0];
Frases[74] = ["La validació del disseny d'un sistema electrònic es fa en el domini estructural.",0];
Frases[75] = ["El PSpice, inclòs a l'OrCAD, és un simulador només elèctric.",0];
Frases[76] = ["El PSpice permet realitzar quatre tipus d'anàlisi diferents: anàlisi temporal o de transitoris ('Time Domain' o 'Transient'), anàlisi de contínua ('DC Sweep'), anàlisi d'alterna o freqüencial ('AC Sweep') i anàlisi del punt de treball ('Bias Point').",1];
Frases[77] = ["Els fitxers de l'OrCAD amb extensió .olb són fitxers de text que contenen els models de simulació elèctrica dels components d'una biblioteca de components.",0];
Frases[78] = ["El disseny de sistemes electrònics inclou cinc grans fases: especificacions, concepció, validació per simulació, construcció d'un prototip i verificació experimental.",1];
Frases[79] = ["El PSpice és un simulador mixt elèctric/lògic que opera en el domini del comportament.",1];
Frases[80] = ["El paquet de CAD electrònic OrCAD de Cadence conté un editor d'esquemàtics, anomenat Capture.",1];
Frases[81] = ["El paquet de CAD electrònic OrCAD de Cadence conté un simulador, anomenat PSpice.",1];
Frases[82] = ["El paquet de CAD electrònic OrCAD de Cadence conté un visualitzador de senyals, anomenat Probe.",1];
Frases[83] = ["El simulador inclòs en el paquet de CAD electrònic OrCAD de Cadence és mixt elèctric/lògic.",1];
Frases[84] = ["En l'OrCAD s'empren biblioteques de símbols i biblioteques de models matemàtics de comportament.",1];
Frases[85] = ["Per simular en l'OrCAD, cal indicar les excitacions a aplicar a les entrades del sistema.",1];
Frases[86] = ["Considerant el disseny de sistemes electrònics, en la fase d'especificacions s'acostuma a definir la funcionalitat del sistema en el domini del comportament.",1];
Frases[87] = ["Considerant el disseny de sistemes electrònics, en la fase de prototipatge cal definir el sistema en el domini físic.",1];
Frases[88] = ["Considerant el disseny de sistemes electrònics, per passar del domini del comportament al domini físic cal passar pel domini estructural, ja sigui de forma explícita o implícita.",1];
Frases[89] = ["La implementació física d'un sistema electrònic pot fer-se per hardware emprant components comercials.",1];
Frases[90] = ["La implementació per hardware d'un sistema electrònic sobre un dispositiu a la mida permet més versatilitat que la seva implementació per hardware sobre un dispositiu programable.",0];
Frases[91] = ["La implementació física d'un sistema electrònic pot fer-se per hardware sobre un dispositiu a la mida.",1];
Frases[92] = ["La implementació per software d'un sistema electrònic sempre requereix la implementació d'un hardware.",1];
Frases[93] = ["S'anomena co-disseny a la implementació combinada per hardware i per software d'un sistema electrònic.",1];
Frases[94] = ["Un oscil·loscopi digital és un aparell destinat a la visualització simultània en una pantalla d'unes poques tensions.",1];
Frases[95] = ["Un oscil·loscopi digital mostreja les tensions d'entrada a alta freqüència, les enregistra en una memòria interna i, posteriorment, les visualitza.",1];
Frases[96] = ["Un oscil·loscopi digital utilitza convertidors analògic-digitals per convertir les tensions d'entrada en informació digital.",1];
Frases[97] = ["Un oscil·loscopi digital permet capturar tensions que no siguin periòdiques, com ara transitoris o esdeveniments que ocorrin només una vegada.",1];
Frases[98] = ["El senyal de rellotge que determina el mostreig de les tensions d'entrada d'un oscil·loscopi digital es genera en un mòdul de l'oscil·loscopi anomenat secció de dispar.",0];
Frases[99] = ["Els pins dels circuits integrats amb encapsulats DIP es numeren de forma correlativa començant per un dels vèrtexs de l'encapsulat i movent-se en sentit horari (vista superior, és a dir, mirant l'encapsulat des de dalt amb els pins cap a baix).",0];
Frases[100] = ["El domini del comportament és el domini del disseny més lligat a la fase d'especificacions.",1];
Frases[101] = ["La secció vertical és una secció d'un oscil·loscopi digital que no existeix en un oscil·loscopi analògic.",0];
Frases[102] = ["La secció horitzontal és una secció d'un oscil·loscopi digital que no existeix en un oscil·loscopi analògic.",0];
Frases[103] = ["La secció de dispar és una secció d'un oscil·loscopi digital que no existeix en un oscil·loscopi analògic.",0];
Frases[104] = ["La secció d'adquisició de dades és una secció d'un oscil·loscopi digital que no existeix en un oscil·loscopi analògic.",1];
Frases[105] = ["La secció de visualització és una secció d'un oscil·loscopi digital que no existeix en un oscil·loscopi analògic.",0];
Frases[106] = ["En l'OrCAD, l'anàlisi de contínua ('DC Sweep') s'empra bàsicament en circuits de caire analògic, els quals se simulen a nivell elèctric.",1];
Frases[107] = ["La validació d'un sistema electrònic es realitza en el domini físic emprant models matemàtics que descriuen les connexions entre els components emprats en el disseny del sistema.",0];
Frases[108] = ["S'anomena circuit imprès a un circuit electrònic implementat sobre un únic cristall de material semiconductor, el qual s'empaqueta adientment emprant encapsulats estandarditzats que disposen de terminals per a les entrades, sortides i alimentacions del circuit.",0];
Frases[109] = ["Els sistemes electrònics s'especifiquen de forma funcional (domini estructural) i es fabriquen seguint una descripció en el domini del comportament, a la que se sol arribar passant pel domini físic.",0];
Frases[110] = ["El domini estructural del disseny d'un sistema electrònic està molt lligat a la concepció de dit sistema.",1];
Frases[111] = ["Un simulador mixt elèctric/lògic combina un simulador elèctric amb un simulador lògic.",1];
Frases[112] = ["Un simulador electrònic requereix una descripció del sistema electrònic.",1];
Frases[113] = ["Un simulador electrònic requereix unes excitacions",1];
Frases[114] = ["Els simuladors electrònics s'empren en la verificació experimental dels sistemes electrònics.",0];
Frases[115] = ["Un simulador electrònic requereix models matemàtics dels components del circuit a simular.",1];
Frases[116] = ["Per simular un circuit amb l'OrCAD cal utilitzar un perfil de simulació.",1];
Frases[117] = ["Existeixen sensors i actuadors fabricats amb material semiconductor.",1];
Frases[118] = ["Amb semiconductors es poden implementar components elèctrics passius, com ara resistències o condensadors.",1];
Frases[119] = ["Els semiconductors poden ser emprats per a connectar elèctricament varis components.",1];
Frases[120] = ["Els semiconductors extrínsecs tipus p s'obtenen dopant els semiconductors purs amb impureses trivalents, com ara el fòsfor.",0];
Frases[121] = ["Es té un cristall amb N àtoms de silici i Y << N àtoms d'impureses acceptadores. En el zero absolut, el cristall té 4 N + 3 Y electrons a la banda de valència i cap electró a la banda de conducció.",1];
Frases[122] = ["En els semiconductors intrínsecs, la concentració d'electrons lliures i la concentració de forats són iguals entre sí.",1];
Frases[123] = ["Els semiconductors extrínsecs tipus n s'obtenen dopant els semiconductors intrínsecs amb impureses trivalents.",0];
Frases[124] = ["En un semiconductor extrínsec tipus p, els ions d'impureses tenen una càrrega elèctrica negativa amb valor absolut igual a cinc vegades el valor absolut de la càrrega elèctrica d'un electró.",0];
Frases[125] = ["La creació de parelles electró-forat en un semiconductor s'anomena ionització, i la desaparició d'aquestes parelles, desionització.",0];
Frases[126] = ["Un semiconductor dopat amb impuresa trivalent és un semiconductor tipus n",0];
Frases[127] = ["A temperatura ambient, la llei de la neutralitat elèctrica per un semiconductor extrínsec tipus p estableix que p + NA = n, on p és la concentració de forats, n és la concentració d'electrons lliures i NA és la concentració d'impureses acceptadores.",0];
Frases[128] = ["En el procés de recombinació que fa desaparèixer, en un semiconductor, una parella electró lliure-forat, s'allibera una energia inferior a l'amplada de la banda prohibida.",0];
Frases[129] = ["Els corrents d'arrossegament d'un semiconductor estan produïts per gradients en les concentracions de portadors de càrrega lliures.",0];
Frases[130] = ["Un semiconductor dopat fortament amb impureses pentavalents presenta una concentració de forats aproximadament igual a la concentració d'impureses acceptadores.",0];
Frases[131] = ["Si un corrent d'arrossegament de forats s'anul·la amb un corrent de difusió de forats, el corrent de forats resultant no provoca efecte Joule.",1];
Frases[132] = ["Suposant totes les impureses ionitzades, la llei de la neutralitat elèctrica per a un semiconductor amb una concentració NA d'impureses acceptadores i una concentració ND d'impureses donadores és p + ND = n + NA.",1];
Frases[133] = ["Si es dopa un cristall de silici amb impuresa pentavalent, tal que la concentració d'impuresa és molt superior a la concentració intrínseca, s'obté un semiconductor extrínsec tipus n.",1];
Frases[134] = ["En un semiconductor extrínsec tipus p a 0 K estan plens tots els nivells energètics de la banda de valència i només ho estan aquests.",1];
Frases[135] = ["En un semiconductor l'efecte Joule degut als forats depèn només del corrent d'arrossegament dels forats.",0];
Frases[136] = ["Un semiconductor extrínsec tipus n, s'obté dopant un semiconductor pur amb impureses pentavalents.",1];
Frases[137] = ["En un semiconductor extrínsec tipus n, quan totes les impureses estan ionitzades, tots els nivells energètics autoritzats dins la banda prohibida situats lleugerament per sota de la banda de conducció estan buits.",1];
Frases[138] = ["En un semiconductor extrínsec tipus n, el producte de la concentració de forats per la concentració d'electrons lliures és superior al quadrat de la concentració intrínseca.",0];
Frases[139] = ["En un semiconductor extrínsec tipus n, cada àtom d'impuresa ionitzat crea localment una càrrega positiva igual al valor absolut de la càrrega d'un electró.",1];
Frases[140] = ["En un semiconductor extrínsec tipus n amb tots els àtoms d'impuresa ionitzats, la concentració d'electrons lliures és superior a la concentració de forats.",1];
Frases[141] = ["Alguns dispositius passius presenten terminals de control.",0];
Frases[142] = ["La grandària d'una resistència està relacionada amb la potència que pot dissipar: quant més voluminosa és, més gran és aquesta potència",1];
Frases[143] = ["Els condensadors no poden presentar variacions brusques (esglaons) en el seu corrent, ja que això comporta una derivada del corrent infinita i, per tant, una tensió infinita, la qual cosa és impossible.",0];
Frases[144] = ["El símbol d'una font dependent de corrent és un cercle amb una fletxa en el seu interior, la qual indica el sentit del corrent que subministra.",0];
Frases[145] = ["El principi de la superposició estableix que la resposta d'un circuit elèctric lineal amb n fonts independents és igual a la suma de les respostes dels n circuits elèctrics obtinguts en considerar efectiva només una de les n fonts i anul·lar totes les altres, és a dir, curtcircuitar les altres fonts de corrent (i = 0) i obrir les altres fonts de tensió (v = 0).",0];
Frases[146] = ["L'anàlisi d'un circuit amb dispositius no lineals es pot fer amb un mètode de prova i error basat en hipòtesis de funcionament en zones de treball caracteritzades per models simples.",1];
Frases[147] = ["Si el guany d'un amplificador és adimensional, es tracta d'un amplificador de transimpedància.",0];
Frases[148] = ["Si el guany d'un amplificador és adimensional, es tracta d'un amplificador de tensió o d'un amplificador de corrent.",1];
Frases[149] = ["Si el guany d'un amplificador és adimensional, es tracta d'un amplificador de transconductància.",0];
Frases[150] = ["Un interruptor ideal és un interruptor controlat bidireccional en tensió i bidireccional en corrent.",1];
Frases[151] = ["Un interruptor ideal és un interruptor controlat unidireccional en tensió i bidireccional en corrent.",0];
Frases[152] = ["Un interruptor ideal és un interruptor controlat bidireccional en tensió i unidireccional en corrent.",0];
Frases[153] = ["Un interruptor ideal és un interruptor controlat unidireccional en tensió i unidireccional en corrent.",0];
Frases[154] = ["Un interruptor ideal és un interruptor no controlat unidireccional en tensió i unidireccional en corrent.",0];
Frases[155] = ["Un dels paràmetres rellevants d'un condensador és la tensió màxima que pot suportar.",1];
Frases[156] = ["Un dels paràmetres rellevants d'un condensador és el seu valor nominal.",1];
Frases[157] = ["Un dels paràmetres rellevants d'un condensador és la seva tolerància.",1];
Frases[158] = ["Un dels paràmetres rellevants d'un condensador és la potència màxima que pot dissipar.",0];
Frases[159] = ["El principi de superposició és aplicable a tot circuit lineal.",1];
Frases[160] = ["Un interruptor és bidireccional en tensió si quan està en OFF és capaç de suportar tensions de qualsevol signe.",1];
Frases[161] = ["En un amplificador de transimpedància, el senyal d'entrada és un corrent i el senyal de sortida és una tensió.",1];
Frases[162] = ["El corrent per una branca d'un circuit no pot presentar esglaons quan la branca inclou una inductància.",1];
Frases[163] = ["Tot dispositiu electrònic de tres terminals es pot modelar amb dues equacions característiques, les quals admeten expressions més simples si es consideren diverses zones de treball per al dispositiu.",1];
Frases[164] = ["La inductància equivalent de dues inductàncies associades en paral·lel és la suma de les dues inductàncies.",0];
Frases[165] = ["Un condensador no pot presentar esglaons en la seva tensió.",1];
Frases[166] = ["Un interruptor ideal es caracteritza, entre d'altres coses, per ser bidireccional tant en tensió com en corrent.",1];
Frases[167] = ["El corrent a través d'una inductància no pot presentar esglaons.",1];
Frases[168] = ["Un interruptor controlat unidireccional en tensió i bidireccional en corrent pot suportar tant corrents positius com corrents negatius amb una caiguda de tensió nul·la.",1];
Frases[169] = ["En augmentar la freqüència, la impedància d'un condensador augmenta mentre que la impedància d'una bobina disminueix.",0];
Frases[170] = ["El díode és un dispositiu electrònic actiu i no lineal.",0];
Frases[171] = ["Els nivells de tensió subministrats per les fonts de tensió emprades per alimentar un amplificador limiten els nivells de tensió assolibles pel senyal de sortida de l'amplificador.",1];
Frases[172] = ["En els amplificadors amb entrada per corrent interessa que la impedància d'entrada sigui molt elevada, a fi de què el màxim del senyal de corrent s'apliqui a l'amplificador.",0];
Frases[173] = ["En els amplificadors amb entrada per corrent interessa que la impedància d'entrada sigui molt petita.",1];
Frases[174] = ["En els amplificadors amb sortida per corrent interessa que la impedància de sortida sigui molt petita.",0];
Frases[175] = ["El guany d'un amplificador amb entrada per tensió i sortida per corrent es mesura en V/A i s'anomena transimpedància.",0];
Frases[176] = ["En un amplificador de corrent interessa que la impedància d'entrada sigui molt petita.",1];
Frases[177] = ["En un amplificador de corrent interessa que la impedància de sortida sigui molt gran.",1];
Frases[178] = ["En un amplificador de tensió, els valors ideals de la impedància d'entrada Zi i de la impedància de sortida Zo són Zi = 0 i Zo = 0.",0];
Frases[179] = ["En un amplificador de tensió, els valors ideals de la impedància d'entrada Zi i de la impedància de sortida Zo són Zi = 0 i Zo = ∞. ",0];
Frases[180] = ["En un amplificador de tensió, els valors ideals de la impedància d'entrada Zi i de la impedància de sortida Zo són Zi = ∞ i Zo = 0.",1];
Frases[181] = ["En un amplificador de tensió, els valors ideals de la impedància d'entrada Zi i de la impedància de sortida Zo són Zi = ∞ i Zo = ∞.",0];
Frases[182] = ["Si el guany d'un amplificador és adimensional, el seu guany és sempre superior a la unitat.",0];
Frases[183] = ["Interessa que un amplificador de transimpedància presenti impedàncies d'entrada i de sortida grans.",0];
Frases[184] = ["La tensió de saturació negativa d'un amplificador alimentat asimètricament entre +VCC i 0 V és una tensió negativa propera a 0 V.",0];
Frases[185] = ["En els circuits amplificadors de tensió, el guany és molt petit per a freqüències prou elevades.",1];
Frases[186] = ["La tensió de sortida vo d'un amplificador de tensió ha de verificar que Vsat− ≤ vo ≤ Vsat+, on Vsat− i Vsat+ són les tensions de saturació de l'amplificador.",1];
Frases[187] = ["Vist des del sistema font que genera el senyal d'entrada, els amplificadors es modelen amb un circuit equivalent de Thévenin o de Norton, on el valor de la font és zero. El model, per tant, només conté una impedància que es coneix amb el nom d'impedància d'entrada.",1];
Frases[188] = ["Perquè el guany d'un amplificador no variï segons la càrrega que se li connecta, és necessari i suficient que la seva impedància d'entrada sigui el més gran possible.",0];
Frases[189] = ["Donat un amplificador de tensió, el seu senyal d'entrada és una tensió generada per un sistema font i el seu senyal de sortida és una tensió que s'aplica sobre un sistema càrrega.",1];
Frases[190] = ["Quan s'aplica una tensió positiva de la regió p a la regió n d'una junció pn, hi ha un corrent net elevat, bàsicament d'arrossegament, que es dirigeix de la regió tipus p a la regió tipus n.",0];
Frases[191] = ["Els díodes Zener estan especialment concebuts per treballar a la zona de ruptura.",1];
Frases[192] = ["Per obtenir en un díode amb η = 1 un corrent IAK igual al corrent invers de saturació IS, n'hi ha prou amb aplicar una tensió VAK de l'ordre de VT (tensió equivalent a la temperatura).",1];
Frases[193] = ["En el model per zones de treball més precís d'un díode Zener, la característica tensió-corrent del díode quan aquest condueix un corrent en inversa s'aproxima amb un circuit constituït per només una font de tensió.",0];
Frases[194] = ["En un díode, el corrent invers tendeix vers el corrent invers de saturació quan la tensió inversa augmenta.",1];
Frases[195] = ["En un díode, l'efecte allau és el responsable de l'elevat corrent directe quan s'apliquen tensions directes elevades.",0];
Frases[196] = ["Els díodes de potència presenten una estructura molt més senzilla que la dels díodes de senyal.",0];
Frases[197] = ["Quan es polaritza un díode en directe, el corrent de difusió augmenta exponencialment amb la tensió directa.",1];
Frases[198] = ["Els díodes Zener estan especialment concebuts per treballar a la zona de saturació.",0];
Frases[199] = ["En un díode en circuit obert, el potencial que hi ha a l'extrem de la zona n allunyat de la junció pn és més alt que el potencial que hi ha a l'extrem de la zona p allunyat de la junció pn.",1];
Frases[200] = ["En un rectificador d'ona completa en pont de Graetz, mai condueixen més de dos díodes.",1];
Frases[201] = ["La grandària d'un díode està en consonància amb el corrent directe màxim que pot suportar.",1];
Frases[202] = ["En un díode, la tensió de ruptura acostuma a ser del mateix ordre de magnitud que la tensió llindar.",0];
Frases[203] = ["S'anomena díode volant al díode que es posa en antiparal·lel amb un interruptor per protegir-lo de sobretensions quan aquest interruptor ha de commutar una càrrega inductiva. ",0];
Frases[204] = ["Els díodes Zener són un tipus de díodes dissenyats per treballar a la zona de ruptura, tot i que en polarització directa es comporten com un díode normal.",1];
Frases[205] = ["Quan es disposa d'una càrrega inductiva alimentada a través d'un interruptor, s'utilitza un díode volant en antiparal·lel amb la càrrega per evitar sobretensions a l'interruptor.",1];
Frases[206] = ["En un MOSFET d'enriquiment de canal n en conducció amb VDS > 0, els electrons van de sortidor a drenador.",1];
Frases[207] = ["El model de petit senyal d'un MOSFET d'enriquiment de canal n a la zona de saturació té un paràmetre que depèn de la tensió VDS.",0];
Frases[208] = ["Un MOSFET d'enriquiment de canal n treballant a la zona de saturació té el canal estrangulat a la zona del sortidor.",0];
Frases[209] = ["Els models de petit senyal dels MOSFETs són vàlids per a variacions suficientment petites de les tensions VGS i VDS",1];
Frases[210] = ["En un transistor MOSFET treballant a la zona òhmica, el canal està parcialment estrangulat.",0];
Frases[211] = ["Es pot implementar una font de corrent constant per a un cert rang de resistències de càrrega amb un circuit que conté un MOSFET treballant a la zona de saturació.",1];
Frases[212] = ["En un MOSFET d'enriquiment de canal n amb tensions VDS > 0, VGS > VT i VGD > VT, on VT és la tensió llindar del MOSFET, hi ha canal en tots els punts situats entre el drenador i la font i la secció útil del canal és menor al drenador que a la font.",1];
Frases[213] = ["El paràmetre gm del model de petit senyal d'un MOSFET d'enriquiment de canal p té per valor ‒K (VGS ‒ VT). ",0];
Frases[214] = ["La conducció a través del canal d'un MOSFET d'enriquiment de canal n amb una tensió llindar VT és deguda a l'arrossegament de forats i el MOSFET està treballant a la zona de saturació quan VGS > VT i VDS ≥ VGS – VT.",0];
Frases[215] = ["La conducció a través del canal d'un MOSFET d'enriquiment de canal n amb una tensió llindar VT és deguda a l'arrossegament de forats i el MOSFET està treballant a la zona de saturació quan VGS < VT i VDS ≤ VGS – VT.",0];
Frases[216] = ["La conducció a través del canal d'un MOSFET d'enriquiment de canal n amb una tensió llindar VT és deguda a l'arrossegament d'electrons i el MOSFET està treballant a la zona de saturació quan VGS > VT i VDS ≥ VGS – VT.",1];
Frases[217] = ["La conducció a través del canal d'un MOSFET d'enriquiment de canal n amb una tensió llindar VT és deguda a l'arrossegament d'electrons i el MOSFET està treballant a la zona de saturació quan VGS < VT i VDS ≤ VGS – VT.",0];
Frases[218] = ["Amb tensions VGS i VDS constants, un MOSFET d'enriquiment de canal n amb una tensió llindar VT pot tenir un corrent de porta no nul en règim permanent.",0];
Frases[219] = ["El component de petit senyal del corrent de porta d'un MOSFET és nul.",1];
Frases[220] = ["El component de petit senyal del corrent de drenador d'un MOSFET és proporcional al component de petit senyal de la tensió porta-sortidor.",1];
Frases[221] = ["El model de petit senyal d'un MOSFET és vàlid només quan el MOSFET treballa a la zona òhmica.",0];
Frases[222] = ["Algun dels paràmetres del model de petit senyal d'un MOSFET depèn del punt de repòs.",1];
Frases[223] = ["Quan es vol que un MOSFET treballi com amplificador, se'l fa treballar a la zona saturació.",1];
Frases[224] = ["En els transistors MOSFET d'empobriment es crea el canal durant la seva fabricació.",1];
Frases[225] = ["En dispositius integrats per molts MOSFETs d'enriquiment de canal n, el substrat és comú a tots ells i es connecta a massa (0 V), treballant-se amb tensions positives en tots els terminals dels MOSFETs.",1];
Frases[226] = ["Quan es vol que el MOSFET d'enriquiment treballi com a dispositiu commutador, només se'l fa treballar en la zona de saturació.",0];
Frases[227] = ["En dispositius integrats per molts MOSFETs, l'estructura d'un MOSFET és simètrica, és a dir els dos extrems poden treballar com a sortidors o com a drenadors.",1];
Frases[228] = ["En un MOSFET d'enriquiment de canal n conduint amb tensió VDS > 0, els electrons es mouen pel canal des del sortidor cap al drenador.",1];
Frases[229] = ["En un MOSFET d'enriquiment de canal n, les regions de drenador i sortidor són de tipus p i el substrat és de tipus n.",0];
Frases[230] = ["Si un MOSFET d'enriquiment de canal n presenta el mateix potencial al terminal de porta que al sortidor, es pot afirmar que està en tall.",1];
Frases[231] = ["En un transistor MOSFET de canal n els portadors majoritaris circulen de drenador a sortidor, mentre que en un de canal p ho fan de sortidor a drenador.",0];
Frases[232] = ["Un transistor MOSFET de canal n amb els terminals drenador i porta units mai podrà treballar en zona òhmica.",1];
Frases[233] = ["La transconductància gm del model de petit senyal d'un MOSFET manté una dependència lineal amb el corrent ID imposat pel circuit de polarització.",0];
Frases[234] = ["Un MOSFET de canal p amb el seus terminals de porta i sortidor connectats entre si sempre treballarà en saturació.",0];
Frases[235] = ["La transconductància gm del model de petit senyal d'un MOSFET de canal n calculada a la zona de saturació és proporcional al quadrat del corrent de drenador ID.",0];
Frases[236] = ["Les tres zones de treball d'un transistor BJT són: tall, activa i saturació.",1];
Frases[237] = ["El transistor BJT es pot modelar com un amplificador de transconductància",0];
Frases[238] = ["El paràmetre β d'un parell Darlington integrat per dos transistors de junció bipolar npn amb paràmetre β = 50 és igual a 100.",0];
Frases[239] = ["Quan es vol que el BJT treballi com a dispositiu amplificador, només se'l fa treballar en la zona de saturació.",0];
Frases[240] = ["La configuració de dos transistors BJT anomenada parell Darlington permet obtenir un valor de β del transistor equivalent molt superior al valor de la β individual dels dos transistors interns.",1];
Frases[241] = ["La corba de potència dissipada màxima que s'utilitza per definir els límits de funcionament d'un transistor de junció bipolar npn és VBE·IC = Pmàx.",0];
Frases[242] = ["La base d'un transistor de junció bipolar npn és terminal de control.",1];
Frases[243] = ["El col·lector d'un transistor de junció bipolar npn és terminal principal.",1];
Frases[244] = ["L'emissor d'un transistor de junció bipolar npn és terminal de control i terminal principal.",1];
Frases[245] = ["Amb VBE > 0 i VCE > 0 i major que unes dècimes de V, el corrent de col·lector d'un transistor de junció bipolar npn és negatiu.",0];
Frases[246] = ["En la zona activa, el corrent de col·lector d'un transistor de junció bipolar npn és proporcional al corrent de base.",1];
Frases[247] = ["El paràmetre β d'un parell Darlington fet amb BJTs amb paràmetres β de valors β1 i β2 és igual a β1 + β2 + β1 β2.",1];
Frases[248] = ["En els transistors BJT pnp, per a VCE > 0 i VBE > 0 suficientment gran (superior a unes dècimes de V), s'obtenen corrents de base IB > 0 i un corrent de col·lector IC > 0 proporcional a IB.",0];
Frases[249] = ["En el model de petit senyal d'un BJT, vbe és proporcional a ib",1];
Frases[250] = ["En un transistor pnp, els portadors de càrrega majoritaris són electrons lliures que es desplacen d'emissor a col·lector quan VCE < 0 i alhora s'injecta un determinat corrent de base.",0];
Frases[251] = ["En un parell Darlington, el paràmetre β del transistor equivalent és igual a β1 + β2, on β1 i β2 són els guanys en la zona activa dels dos transistors del parell.",0];
Frases[252] = ["La tensió de saturació d'un parell Darlington format per dos transistors npn iguals sempre és més gran que la tensió de saturació que presenta cada transistor individualment.",1];
Frases[253] = ["Si un transistor de junció bipolar presenta una tensió |VCE| > |VCEsat|, es pot assegurar que es troba treballant a la zona activa.",0];
Frases[254] = ["Donats dos corrents de base IB1 i IB2, amb IB1 < IB2, la característica de sortida de tot transistor BJT per a IB1 està més pròxima a l'eix horitzontal IC = 0 que la característica de sortida per a IB2.",0];
Frases[255] = ["Si un transistor bipolar npn (VBE0 = 0,7 V i VCEsat = 0,2 V) presenta unes tensions VCE < VBE, llavors es pot assegurar que es troba en saturació.",0];
Frases[256] = ["Els transistors BJT poden ser de tipus pnp o npn.",1];
Frases[257] = ["En els transistors BJT treballant en saturació, la tensió VCE és aproximadament constant.",1];
Frases[258] = ["En els transistors BJT treballant a la zona activa, el corrent IC és proporcional a IB.",1];
Frases[259] = ["La característica d'entrada de tot transistor BJT presenta el mateix patró que la característica d'un díode.",1];
Frases[260] = ["Els transistors MOSFET i BJT treballen com a dispositius amplificadors a la zona de saturació.",0];
Frases[261] = ["De l'anàlisi en corrent continu d'un circuit amplificador de tensió implementat amb un BJT, es dedueix que el transistor treballa al voltant d'un punt d'operació situat en la zona activa, que ha d'estar situat el més a prop possible de la zona de saturació.",0];
Frases[262] = ["En l'anàlisi de corrent altern d'un circuit amplificador de tensió implementat amb un BJT, el transistor se substitueix pel seu model de petit senyal, format per una resistència i una font de corrent dependent.",1];
Frases[263] = ["De vegades, els circuits amplificadors de tensió implementats amb transistors BJT incorporen condensadors de desacoblament.",1];
Frases[264] = ["Els circuits amplificadors de tensió implementats amb transistors BJT incorporen una font de tensió de corrent continu.",1];
Frases[265] = ["En els circuits amplificadors de tensió implementats amb transistors BJT interessa que la seva impedància d'entrada sigui la més gran possible i que la seva impedància de sortida sigui la més petita possible.",1];
Frases[266] = ["El model de petit senyal es fa servir quan els transistors MOSFET i BJT treballen com a dispositius commutadors.",0];
Frases[267] = ["L'IGBT es pot modelar amb dos transistor BJT funcionant amb un mecanisme de realimentació regenerativa.",0];
Frases[268] = ["Un IGBT és un transistor de senyal que combina en un únic dispositiu el bo i millor d'un BJT de senyal i un MOSFET de senyal.",0];
Frases[269] = ["Un interruptor controlat bàsic (transistor) més un interruptor no controlat (díode) connectats en sèrie formen un interruptor controlat unidireccional en tensió i bidireccional en corrent.",0];
Frases[270] = ["Per controlar l'estat d'un interruptor implementat amb un transistor cal disposar d'un circuit de polarització que situï el punt de treball al mig de la recta de càrrega.",0];
Frases[271] = ["L'IGBT és un dispositiu actiu amb tres terminals que només s'utilitza com a dispositiu commutador en els sistemes electrònics de potència i que es controla per tensió.",1];
Frases[272] = ["El comportament d'un transistor de junció bipolar s'acosta al d'un interruptor controlat unidireccional en corrent i bidireccional en tensió.",0];
Frases[273] = ["Els transistors de junció bipolar de senyal tenen una freqüència de commutació més gran que els transistors MOSFET de senyal.",1];
Frases[274] = ["Un MOSFET de potència actua com un interruptor controlat per tensió, bidireccional en tensió i unidireccional en corrent.",0];
Frases[275] = ["L'IGBT es pot modelar amb un circuit, basat en un transistor MOSFET d'enriquiment de canal n i un transistor BJT pnp, que presenta dues branques per les que circula el corrent ID o IC de l'IGBT.",1];
Frases[276] = ["Els transistors BJT de potència presenten una major facilitat de control que els MOSFET de potència.",0];
Frases[277] = ["La porta d'un IGBT és terminal de control.",1];
Frases[278] = ["El drenador d'un IGBT també es pot anomenar col·lector.",1];
Frases[279] = ["La tensió VGS d'un IGBT ha de ser positiva perquè l'IGBT condueixi.",1];
Frases[280] = ["Un IGBT és més ràpid que un MOSFET de potència.",0];
Frases[281] = ["Els BJTs i els MOSFETs presents en circuits integrats es poden comportar, aproximadament, com interruptors controlats unidireccionals en tensió i en corrent.",1];
Frases[282] = ["Les freqüències màximes de commutació dels BJTs de potència són més altes que les freqüències màximes de commutació dels MOSFETs de potència.",0];
Frases[283] = ["Quan un dispositiu electrònic actua com a interruptor, sempre és bidireccional en tensió.",0];
Frases[284] = ["Els MOSFETs de potència treballant en commutació es comporten com interruptors controlats unidireccionals en tensió i bidireccionals en corrent.",1];
Frases[285] = ["El circuit de control d'un MOSFET treballant com interruptor pot consistir en una font de corrent variable ideal.",0];
Frases[286] = ["Un MOSFET que treballa com a interruptor ho farà en les regions de saturació i tall.",0];
Frases[287] = ["Un transistor bipolar treballant com a interruptor, amb corrent de base negligible, presentarà unes pèrdues en conducció de valor VCEsat·IC.",1];
Frases[288] = ["En un TRIAC es pot controlar l'apagat del dispositiu mitjançant un pols de corrent negatiu pel terminal de porta.",0];
Frases[289] = ["En el control de la lluminositat d'una bombeta amb un SCR, a mesura que s'incrementa l'angle d'encesa α ∈ [0º, 180º], la potència entregada a la càrrega augmenta.",0];
Frases[290] = ["Un SCR es pot modelar amb dos BJTs realimentats mútuament, un pnp i l'altre npn, tal que la base de cada un d'ells està connectada al col·lector de l'altre",1];
Frases[291] = ["Des d'un punt de vista funcional, un TRIAC ('TRIode for Alternating Current') és equivalent a dos SCRs ('Silicon Controlled Rectifier') connectats en antiparal·lel que comparteixen el terminal de control G.",1];
Frases[292] = ["Per mantenir encès un SCR cal mantenir un pols de corrent pel terminal de porta.",0];
Frases[293] = ["En els SCRs, si se supera una dVAK/dt màxima en la regió OFF+, es produeix una transició a la regió ON+.",1];
Frases[294] = ["El GTO ('Gate Turn-Off thyristor') és una variant de l'SCR que permet una apagada controlada del dispositiu mitjançant la injecció d'un pols negatiu de corrent pel seu terminal de porta.",1];
Frases[295] = ["El TRIAC és un dispositiu actiu amb tres terminals, anomenats G, T2 i T1, que treballa com a dispositiu commutador.",1];
Frases[296] = ["La característica de sortida d'un TRIAC presenta quatre zones de treball, dues corresponents a la conducció (ON+ i ON–) i les altres dues a la no conducció o bloqueig (OFF+ i OFF–).",1];
Frases[297] = ["Quan la tensió VT2T1 entre els terminals T2 i T1 d'un TRIAC és positiva, no es passa de bloqueig (OFF+) a conducció (ON+) en aplicar polsos de corrent negatius prou energètics pel terminal G.",0];
Frases[298] = ["Quan la tensió VT2T1 entre els terminals T2 i T1 d'un TRIAC és positiva, es passa de bloqueig (OFF+) a conducció (ON+) en aplicar polsos de corrent positius prou energètics pel terminal G.",1];
Frases[299] = ["La característica de sortida d'un SCR presenta tres regions o zones de treball: ON+, OFF+ i OFF‒.",1];
Frases[300] = ["Un SCR treballa com a dispositiu commutador d'alta freqüència. ",0];
Frases[301] = ["No es pot controlar l'apagada o bloqueig d'un SCR mitjançant el seu terminal de porta.",1];
Frases[302] = ["En un SCR, no cal mantenir el senyal de control a un nivell predeterminat durant l'estat de conducció.",1];
Frases[303] = ["El TRIAC és un component actiu.",1];
Frases[304] = ["El TRIAC té tres terminals, anomenats porta, ànode i càtode.",0];
Frases[305] = ["El TRIAC es controla mitjançant el corrent pel terminal de porta. ",1];
Frases[306] = ["Estant en conducció, el TRIAC es bloqueja quan el corrent que hi circula es fa més petit que un valor característic anomenat corrent de manteniment IH",1];
Frases[307] = ["La freqüència de commutació dels SCRs és inferior a la dels MOSFETs i BJTs de potència.",1];
Frases[308] = ["Els SCRs tenen tres terminals, anomenats ànode, càtode i porta.",1];
Frases[309] = ["Un SCR treballa com un interruptor controlat bidireccional en tensió i unidireccional en corrent.",1];
Frases[310] = ["Un SCR es bloqueja quan el corrent que hi circula es fa inferior a un corrent petit anomenat corrent d'enclavament (IL).",0];
Frases[311] = ["Un SCR pot passar a conduir a conseqüència d'esglaons de la tensió VAK",1];
Frases[312] = ["La característica de sortida d'un TRIAC presenta una zona de conducció en directa",1];
Frases[313] = ["La característica de sortida d'un TRIAC presenta una zona de conducció en inversa.",1];
Frases[314] = ["La característica de sortida d'un TRIAC presenta una zona de bloqueig en directa.",1];
Frases[315] = ["La característica de sortida d'un TRIAC presenta una zona de bloqueig en inversa.",1];
Frases[316] = ["El corrent de porta IG d'un TRIAC ha de ser sempre més gran o igual que zero.",0];
Frases[317] = ["La característica d'entrada d'un SCR relaciona el corrent IG amb la tensió VGK i es pot aproximar per una recta que passa per l'origen.",1];
Frases[318] = ["Entre els límits de funcionament d'un SCR es troba el paràmetre dVAK/dt màxima en la regió OFF+ que, en superar-se, dona lloc a una transició de la regió OFF+ a la regió ON+.",1];
Frases[319] = ["Un GTO ('Gate Turn-Off') és un tipus de tiristor.",1];
Frases[320] = ["Tots els tiristors tenen quatre o més regions diferenciades de material semiconductor.",1];
Frases[321] = ["Els noms dels terminals d'un SCR són els mateixos que els d'un TRIAC.",0];
Frases[322] = ["Des d'un punt de vista funcional, un TRIAC equival a dos SCRs connectats en antiparal·lel que comparteixen el terminal de control G.",1];
Frases[323] = ["El corrent d'enclavament IL d'un SCR és més gran que el seu corrent de manteniment IH.",1];
Frases[324] = ["La característica d'entrada d'un SCR sol modelar-se amb una recta VGK = RGK IG compresa entre dues rectes extremes que passen per l'origen subministrades pel seu fabricant.",1];
Frases[325] = ["Un TRIAC és un dispositiu electrònic de tres terminals que pot bloquejar tensions positives i negatives entre els seus terminals principals i pot conduir corrent en tots dos sentits.",1];
Frases[326] = ["En un SCR, és necessari mantenir contínuament un corrent de porta IG superior al corrent de manteniment IH perquè el dispositiu es mantingui en conducció.",0];
Frases[327] = ["Un TRIAC és un interruptor controlat bidireccional tant en tensió com en corrent.",1];
Frases[328] = ["Un SCR és un dispositiu electrònic amb tres terminals anomenats ànode, càtode i porta.",1];
Frases[329] = ["L'estructura d'un SCR es modela mitjançant dos BJTs que es realimenten mútuament, un de tipus pnp i l'altre de tipus npn. ",1];
Frases[330] = ["Un SCR pot romandre en conducció, tot i presentar un corrent de porta igual a zero.",1];
Frases[331] = ["Alguns SCR poden conduir corrents superiors a 1 kA i bloquejar tensions superiors a 1 kV.",1];
Frases[332] = ["En un SCR, la transició de la regió de conducció a la regió de bloqueig es produeix de forma espontània quan el circuit extern força IA < IL (corrent d'enclavament) durant prou temps.",0];
Frases[333] = ["En un SCR té lloc un fenomen físic anomenat efecte tiristor.",1];
Frases[334] = ["Un TRIAC és un dispositiu actiu que presenta tres terminals anomenats A, K i G.",0];
Frases[335] = ["Un SCR es comporta com un interruptor controlat bidireccional en tensió i unidireccional en corrent. ",1];
Frases[336] = ["Un TRIAC es comporta com un interruptor controlat bidireccional en tensió i bidireccional en corrent.",1];
Frases[337] = ["Un SCR es pot disparar (passar a la conducció de forma controlada) només en el primer quadrant (VAK > 0 i IG > 0), mentre que un TRIAC es pot disparar en els quatre quadrants.",1];
Frases[338] = ["En un LED, la longitud d'ona de la llum emesa depèn del material semiconductor emprat per construir-lo.",1];
Frases[339] = ["En un LED, la caiguda de tensió quan el dispositiu condueix depèn del material semiconductor emprat per construir-lo.",1];
Frases[340] = ["La lluminositat d'un LED disminueix en augmentar el corrent directe pel LED.",0];
Frases[341] = ["Un LED simple emet radiació electromagnètica amb un espectre freqüencial estret.",1];
Frases[342] = ["Els optoacobladors o fotoacobladors serveixen per transferir senyals elèctrics d'un circuit a un altre aïllat elèctricament del primer.",1];
Frases[343] = ["Quan un fotodíode s'empra per mesurar, de la forma més sensible possible, la intensitat de la llum, se'l fa treballar en el tercer quadrant (VAK < 0 i IAK < 0).",1];
Frases[344] = ["En els set-segments en ànode comú, els ànodes de tots els LEDs que l'integren estan connectats entre si, accedint-se a tots ells mitjançant un terminal anomenat ànode (A), el qual es connecta al terminal negatiu de l'alimentació del circuit (0 V o massa).",0];
Frases[345] = ["El set-segments és un visualitzador format per 7 LEDs distribuïts de forma adient per tal de poder representar dígits decimals (o 8 LEDs si també hi ha punt decimal).",1];
Frases[346] = ["Els LEDs que emeten llum visible es fabriquen amb silici.",0];
Frases[347] = ["El fototransistor és més sensible que el fotodíode degut al guany propi del transistor.",1];
Frases[348] = ["El mecanisme mitjançant el qual els LEDs emeten llum està relacionat amb el procés de recombinació dels portadors (forats i electrons) quan els LEDs es polaritzen en directa.",1];
Frases[349] = ["Dels semiconductors Ge, Si, Ga As, Ga P i Si C, el que permet la fabricació de LEDs emissors de fotons de longitud d'ona més gran és el Ge.",1];
Frases[350] = ["El fototransistor és un dispositiu que combina un LED i un transistor bipolar.",0];
Frases[351] = ["Els LEDs vermell, verd, groc i blau es construeixen amb silici.",0];
Frases[352] = ["Un optoacoblador és un dispositiu fotoelectrònic que conté una combinació d'un LED amb un fototransistor.",1];
Frases[353] = ["Un sensor per reflexió de la llum és un dispositiu fotoelectrònic que conté una combinació d'un LED amb un fototransistor.",1];
Frases[354] = ["Un fotoacoblador és un dispositiu fotoelectrònic que conté una combinació d'un LED amb un fototransistor.",1];
Frases[355] = ["Una barrera de llum és un dispositiu fotoelectrònic que conté una combinació d'un LED amb un fototransistor.",1];
Frases[356] = ["Una cel·la fotovoltaica és un dispositiu fotoelectrònic que conté una combinació d'un LED amb un fototransistor.",0];
Frases[357] = ["Si un LED està treballant a la zona de conducció, el corrent i el fenomen de la ionització són molt importants i hi ha emissió de fotons (LED encès).",0];
Frases[358] = ["Un optoacoblador permet transmetre informació entre dos circuits elèctrics que es troben aïllats elèctricament l'un de l'altre. La transmissió d'informació es fa modulant la llum emesa pel LED, la qual es rebuda per un fototransistor.",1];
Frases[359] = ["Un fotodíode pot treballar amb tensions VAK positives i corrents IAK positius.",1];
Frases[360] = ["Un fotodíode pot treballar amb tensions VAK positives i corrents IAK negatius.",1];
Frases[361] = ["Un fotodíode pot treballar amb tensions VAK negatives i corrents IAK negatius.",1];
Frases[362] = ["Un fotodíode pot treballar amb tensions VAK negatives i corrents IAK positius.",0];
Frases[363] = ["Un fotodíode, si s'implementa amb silici, és sensible a la llum infraroja.",1];
Frases[364] = ["Un optoacoblador és una agrupació d'un fotodíode i un fototransistor muntada en un mateix encapsulat de forma que la llum es transmet per dins de l'encapsulat.",0];
Frases[365] = ["En un LED, la longitud d'ona de la llum emesa depèn del salt energètic EG entre les bandes de valència i de conducció del material semiconductor emprat per construir-lo.",1];
Frases[366] = ["Un LED RGB és una agrupació de tres LEDs, un de vermell, un de verd i un de blau que comparteixen encapsulat.",1];
Frases[367] = ["Un visualitzador set segments pot set de tipus ànode comú o càtode comú en funció de com es connectin els LEDs internament. ",1];
Frases[368] = ["Existeixen agrupacions de LEDs que permeten representar caràcters alfanumèrics.",1];
Frases[369] = ["Es pot detectar la presència de llum amb un fotodíode.",1];
Frases[370] = ["Les cel·les fotovoltaiques entreguen energia elèctrica obtinguda a partir de la radiació solar que incideix sobre les mateixes.",1];
Frases[371] = ["Un optoacoblador o fotoacoblador serveix per detectar la presència de cossos opacs.",0];
Frases[372] = ["Un fototransistor es modela amb un fotodíode i un transistor.",1];
Frases[373] = ["En absència de llum, un fotodíode es comporta com un díode normal.",1];
Frases[374] = ["L'efecte de la potència lumínica rebuda per un fotodíode es pot modelar amb un corrent invers addicional que és més gran quan més gran és la potència lumínica rebuda pel fotodíode.",1];
Frases[375] = ["Un fotodíode està muntat sobre un encapsulat que deixa passar la llum.",1];
Frases[376] = ["Un fotodíode treballant en el quart quadrant de (VAK,I), on I és el corrent directe, rep energia elèctrica.",0];
Frases[377] = ["Una cel·la fotovoltaica és un fotodíode construït per treballar transformant energia lluminosa en energia elèctrica.",1];



/*Frases[] = ["",];*/

var Q = Frases.length;
var Aleatori = Math.round(Math.random()*(Q-1));
/*function ShowFrase(){
	document.write(Frases[Aleatori][0]);
}*/
document.getElementById("idfrases").innerHTML = Frases[Aleatori][0];

var errades = 0;
var correctes = 0;

document.getElementById("verdader").addEventListener("click", function(){resposta(1);});
document.getElementById("fals").addEventListener("click", function(){resposta(0);});
document.getElementById("seguent").addEventListener("click", function(){passa()});

function resposta(res){
	if(res == Frases[Aleatori][1]) {
		document.getElementById("solucio").innerHTML = "Correcte!";
		document.getElementById("fals").disabled = true;
		document.getElementById("verdader").disabled = true;
		correctes++;
		Frases[Aleatori][1] = 2 /**/
		document.getElementById("estanbe").innerHTML = "Correctes: "+correctes;
		document.getElementById("estanmalament").innerHTML = "Errades: "+errades;
	}
	else if(res != Frases[Aleatori][1]) {
		document.getElementById("solucio").innerHTML = "Nooo! Malament!";
		document.getElementById("fals").disabled = true;
		document.getElementById("verdader").disabled = true;
		errades++;
		document.getElementById("estanbe").innerHTML = "Correctes: "+correctes;
		document.getElementById("estanmalament").innerHTML = "Errades: "+errades;
	}
}

function passa(){
	if(correctes == Q) acaba(); /**/
	else { /**/
		Aleatori = Math.round(Math.random()*(Q-1));
		if(Frases[Aleatori][1] == 2) passa2(); /**/
		else{ /**/
			document.getElementById("idfrases").innerHTML = Frases[Aleatori][0];
			document.getElementById("solucio").innerHTML = "";
			document.getElementById("verdader").disabled = false;
			document.getElementById("fals").disabled = false;
		}
	}
}

function passa2(){
	Aleatori++;
	if (Aleatori>=Q) Aleatori = 0;
	if(Frases[Aleatori][1] == 2) passa2();
	else {
		document.getElementById("idfrases").innerHTML = Frases[Aleatori][0];
		document.getElementById("solucio").innerHTML = "";
		document.getElementById("verdader").disabled = false;
		document.getElementById("fals").disabled = false;
	}
}

function acaba(){
	document.getElementById("idfrases").innerHTML = "Felicitats! Has endevinat totes les frases que hi havia disponibles! Cada cop estàs més preparat per l'examen.";
	document.getElementById("seguent").innerHTML = "Acabat";
	document.getElementById("seguent").disabled = true;
}